#!/bin/bash
#title          :webp2gif
#description    :convert animated webp to gif
#author         :elsonwx
#date           :20200205
#usage          :webp2gif input.webp output.gif
#==============================================================================
version=0.1
if [[ $1 == "-v" ]];then
    echo "version:$version"
    exit 0
fi
cur_dir=$(pwd)
temp_dir=$(mktemp -d)
cd $temp_dir
webpfile=$1
if [[ ! -f $webpfile ]];then
    webpfile=$cur_dir/$webpfile
fi
frames_num=$(webpmux -info $webpfile|sed -n 's/Number of frames: //p')
table_line=$(webpmux -info $webpfile|grep -nh  "No.: width.*"|cut -d : -f 1)
for i in $(seq 1 $frames_num);do
    webpmux -get frame $i $webpfile -o "$i.webp"
    width=$(webpmux -info $webpfile|awk -v cur_line="$((table_line+i))" '{if(NR==cur_line) print $2}')
    offset_x=$(webpmux -info $webpfile|awk -v cur_line="$((table_line+i))" '{if(NR==cur_line) print $5}')
    new_width=$((width+offset_x))
    height=$(webpmux -info $webpfile|awk -v cur_line="$((table_line+i))" '{if(NR==cur_line) print $3}')
    offset_y=$(webpmux -info $webpfile|awk -v cur_line="$((table_line+i))" '{if(NR==cur_line) print $6}')
    blend=$(webpmux -info $webpfile|awk -v cur_line="$((table_line+i))" '{if(NR==cur_line) print $9}')
    new_height=$((height+offset_y))
    dwebp "$i.webp" -o "x$i.png"
    convert -gravity southeast -extent ${new_width}x${new_height} -background none "x$i.png" "b$i.png"
    if [[ $blend = no ]];then
        cp "b$i.png" "f$i.png"
    else
        composite -gravity northwest -compose atop "b$i.png" "f$((i-1)).png" "f$i.png"
    fi
done
for i in {1..99}
do
    if [[ -f "x$i.png" ]];then
        if [[ i -lt 10 ]];then
            mv "b$i.png" "b00$i.png"
            mv "f$i.png" "f00$i.png"
        else
            mv "b$i.png" "b0$i.png"
            mv "f$i.png" "f0$i.png"
        fi
    fi
done
echo "converting all png frame file to gif..."
convert -delay 0 -loop 0 b*.png animation.gif
convert -delay 0 -loop 0 f*.png animation2.gif
cp $temp_dir/animation.gif $cur_dir/$2
#rm -rf $temp_dir
echo $temp_dir
rm *.webp
rm x*.png
rm b*.png
ls *.png >doit.sh
chmod +x doit.sh
echo "finished with success!"
